// ---------------------------------------------------------------------------
// Supabase Edge Function: weakness-report
//
// Optional server-side mirror of the analysis in src/lib/engine.ts. Useful if
// you want reports generated by the database rather than the Next.js app
// (e.g. from a Postgres trigger, a cron job, or a mobile client).
//
//   supabase functions deploy weakness-report
//   curl -X POST "$SUPABASE_URL/functions/v1/weakness-report" \
//        -H "Authorization: Bearer $SERVICE_ROLE" \
//        -d '{"session_id":"..."}'
// ---------------------------------------------------------------------------
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

interface AnswerRow {
  is_correct: boolean | null;
  selected_option: string | null;
  time_taken_ms: number | null;
  questions: { topic: string; subject: string; difficulty: string } | null;
}

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") return new Response("Method not allowed", { status: 405 });

  const { session_id } = await req.json();
  if (!session_id) return Response.json({ error: "session_id is required" }, { status: 400 });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  const { data: session, error: sessionErr } = await supabase
    .from("practice_sessions")
    .select("id, user_id, exam")
    .eq("id", session_id)
    .single();
  if (sessionErr || !session) return Response.json({ error: "Session not found" }, { status: 404 });

  const { data: answers, error } = await supabase
    .from("session_answers")
    .select("is_correct, selected_option, time_taken_ms, questions ( topic, subject, difficulty )")
    .eq("session_id", session_id);
  if (error) return Response.json({ error: error.message }, { status: 500 });

  const { data: settings } = await supabase
    .from("app_settings")
    .select("weakness_threshold")
    .eq("id", "singleton")
    .maybeSingle();
  const threshold = settings?.weakness_threshold ?? 50;

  type Bucket = { subject: string; total: number; wrong: number; correct: number; skipped: number; missedEasy: number };
  const stats: Record<string, Bucket> = {};

  for (const a of (answers ?? []) as unknown as AnswerRow[]) {
    const q = a.questions;
    if (!q) continue;
    const b = (stats[q.topic] ??= { subject: q.subject, total: 0, wrong: 0, correct: 0, skipped: 0, missedEasy: 0 });
    b.total++;
    if (!a.selected_option) b.skipped++;
    else if (a.is_correct) b.correct++;
    else {
      b.wrong++;
      if (q.difficulty === "easy") b.missedEasy++;
    }
  }

  const rows = Object.entries(stats).map(([topic, b]) => {
    const effectiveWrong = b.wrong + b.skipped * 0.5;
    const score = Math.max(0, Math.min(100, Math.round((effectiveWrong / b.total) * 100) + b.missedEasy * 5));
    return {
      user_id: session.user_id,
      session_id,
      exam: session.exam,
      subject: b.subject,
      topic,
      weakness_score: score,
      total_attempted: b.total,
      correct_count: b.correct,
      wrong_count: b.wrong,
      severity: score >= 75 ? "critical" : score >= 50 ? "weak" : score >= 25 ? "fair" : "strong",
      recommendation:
        score >= threshold
          ? `Revise ${topic} carefully, then drill 10-15 questions on it alone.`
          : `${topic} looks stable — keep it warm with short weekly drills.`,
    };
  });

  const weak = rows.filter((r) => r.weakness_score >= threshold).sort((a, b) => b.weakness_score - a.weakness_score);

  // attach a matching textbook chapter where one exists
  for (const r of rows) {
    const { data: tb } = await supabase
      .from("textbooks")
      .select("id")
      .eq("is_published", true)
      .contains("topic_tags", [r.topic])
      .limit(1)
      .maybeSingle();
    (r as Record<string, unknown>).textbook_id = tb?.id ?? null;
  }

  const keep = rows.filter((r) => r.weakness_score >= 25);
  if (keep.length) await supabase.from("weakness_reports").insert(keep);

  return Response.json({ ok: true, weaknesses: weak, analysed: rows.length });
});
